name: Build Predictions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours

permissions:
  contents: write

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scikit-learn
      - name: Build predictions.json
        run: |
          python3 scripts/predict.py
      - name: Commit predictions
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add predictions.json
            git commit -m "chore(predictions): update predictions.json"
            git push
          else
            echo "No changes to commit"
          fi
